[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  VITE_API_URL = "https://padre-ginos-fem.onrender.com"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirect API requests to the backend
[[redirects]]
  from = "/api/*"
  to = "https://padre-ginos-fem.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Redirect public files to the backend
[[redirects]]
  from = "/public/*"
  to = "https://padre-ginos-fem.onrender.com/public/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Set security headers for all routes
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Forwarded-For"
    Content-Security-Policy = """
      default-src 'self' https://padre-ginos-fem.onrender.com;
      img-src 'self' https://padre-ginos-fem.onrender.com data: https:;
      style-src 'self' 'unsafe-inline' https:;
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      connect-src 'self' https://padre-ginos-fem.onrender.com;
      font-src 'self' data: https:;
      """ 