[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://padre-ginos-fem.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*" 